[font]
size = 12

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Light Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "Light"
